### ISSUE TITLE
[nuxt-booster]  ERROR  can't embed css file. Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by chaderenyore** [basics/nuxt-booster#1106]
**Describe the bug**
After using Nuxt-booster to improve my website, It ran well on development. But when building for production it gives me an error that doesn't stop the build process.

```
[nuxt-booster 13:13:58]  ERROR  can't embed css file. Cannot read properties of null (reading 'map')

  at prepareUrls (/home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nuxt-booster/dist/module.mjs:287:15)
  at /home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nuxt-booster/dist/module.mjs:309:16
  at async Promise.all (index 0)
  at async prepareLinkStylesheets (/home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nuxt-booster/dist/module.mjs:303:17)
  at async /home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nuxt-booster/dist/module.mjs:279:5
  at async generateRoute (/home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nitropack/dist/chunks/prerender.mjs:161:5)
  at async Promise.all (index 0)
  at async runParallel (/home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nitropack/dist/chunks/prerender.mjs:251:3)
  at async prerender (/home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nitropack/dist/chunks/prerender.mjs:200:3)
  at async /home/nyore/Desktop/Programming/Client%20Projects/ineodev_nuxtjs/nuxtjs/node_modules/nuxt/dist/index.mjs:3471:7

```

**To Reproduce**

**Expected behavior**
Normally I'm not supposed to have these errors, and I need to clean it up for my client.

**Screenshots**
![NuxtBoosterError](https://github.com/user-attachments/assets/e2d42faf-fde4-4d57-900a-cbbafd71d5f6)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [3.0.14]

**Additional context**
This error though doesn't stop the build process, so if there's way I can fix the issues then very fine, if not then git rid of the errors or suppress it somehow.

**Comment by chaderenyore** [comment]
Updating to the latest version of nuxt of nuxt booster fixed it for me. The error was gone.
